title: Il Libro Open Source

theme: just-the-docs
baseUrl: "/book"
url: "https://il-libro-open-source.github.io"

permalink: pretty

search_enabled: true

back_to_top: true
back_to_top_text: "Torna all'inizio"

footer_content: "Copyright &copy; 2023-2025 Il Libro Open Source"

gh_edit_link: true
gh_edit_link_text: "Contribuisci a questo contenuto su GitHub."
gh_edit_repository: "https://github.com/Il-Libro-Open-Source/book"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
